version: "3.8"

services:
  nifi:
    image: apache/nifi:2.3.0
    container_name: nifi
    restart: on-failure
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=nifi
      - SINGLE_USER_CREDENTIALS_PASSWORD=nifi12345678
    networks:
      - nifi_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto
    ports:
      - "5433:5432"
    networks:
      - nifi_network

networks:
  nifi_network:

